server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789@Mk
    url: jdbc:mysql://localhost:3306/new_projects?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
logging:  
     level:
        org:
         springframawork: info
         hibernate: error
     resources:
            add-mappings: true
jwt:
  secret: manikanta
  

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
